[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mubashir123/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "scripts/init.ts"

[workspace]
members = [
    "programs/swap"
]

[toolchain]
anchor_version = "0.28.0"
