global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # NovaDex Application Metrics
  - job_name: 'novadex-app'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: /api/metrics
    scrape_interval: 30s

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Application Health Checks
  - job_name: 'novadex-health'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: /api/health
    scrape_interval: 10s
